/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  java.lang.CharSequence
 *  java.lang.Object
 *  java.util.Collections
 *  java.util.HashMap
 *  java.util.Map
 *  java.util.Map$Entry
 *  java.util.stream.Collectors
 */
package org.apache.commons.text.translate;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;

public class EntityArrays {
    public static final Map<CharSequence, CharSequence> ISO8859_1_ESCAPE;
    public static final Map<CharSequence, CharSequence> ISO8859_1_UNESCAPE;
    public static final Map<CharSequence, CharSequence> HTML40_EXTENDED_ESCAPE;
    public static final Map<CharSequence, CharSequence> HTML40_EXTENDED_UNESCAPE;
    public static final Map<CharSequence, CharSequence> BASIC_ESCAPE;
    public static final Map<CharSequence, CharSequence> BASIC_UNESCAPE;
    public static final Map<CharSequence, CharSequence> APOS_ESCAPE;
    public static final Map<CharSequence, CharSequence> APOS_UNESCAPE;
    public static final Map<CharSequence, CharSequence> JAVA_CTRL_CHARS_ESCAPE;
    public static final Map<CharSequence, CharSequence> JAVA_CTRL_CHARS_UNESCAPE;

    public static Map<CharSequence, CharSequence> invert(Map<CharSequence, CharSequence> map) {
        return (Map)map.entrySet().stream().collect(Collectors.toMap(Map.Entry::getValue, Map.Entry::getKey));
    }

    static {
        HashMap initialMap = new HashMap();
        initialMap.put((Object)" ", (Object)"&nbsp;");
        initialMap.put((Object)"¡", (Object)"&iexcl;");
        initialMap.put((Object)"¢", (Object)"&cent;");
        initialMap.put((Object)"£", (Object)"&pound;");
        initialMap.put((Object)"¤", (Object)"&curren;");
        initialMap.put((Object)"¥", (Object)"&yen;");
        initialMap.put((Object)"¦", (Object)"&brvbar;");
        initialMap.put((Object)"§", (Object)"&sect;");
        initialMap.put((Object)"¨", (Object)"&uml;");
        initialMap.put((Object)"©", (Object)"&copy;");
        initialMap.put((Object)"ª", (Object)"&ordf;");
        initialMap.put((Object)"«", (Object)"&laquo;");
        initialMap.put((Object)"¬", (Object)"&not;");
        initialMap.put((Object)"­", (Object)"&shy;");
        initialMap.put((Object)"®", (Object)"&reg;");
        initialMap.put((Object)"¯", (Object)"&macr;");
        initialMap.put((Object)"°", (Object)"&deg;");
        initialMap.put((Object)"±", (Object)"&plusmn;");
        initialMap.put((Object)"²", (Object)"&sup2;");
        initialMap.put((Object)"³", (Object)"&sup3;");
        initialMap.put((Object)"´", (Object)"&acute;");
        initialMap.put((Object)"µ", (Object)"&micro;");
        initialMap.put((Object)"¶", (Object)"&para;");
        initialMap.put((Object)"·", (Object)"&middot;");
        initialMap.put((Object)"¸", (Object)"&cedil;");
        initialMap.put((Object)"¹", (Object)"&sup1;");
        initialMap.put((Object)"º", (Object)"&ordm;");
        initialMap.put((Object)"»", (Object)"&raquo;");
        initialMap.put((Object)"¼", (Object)"&frac14;");
        initialMap.put((Object)"½", (Object)"&frac12;");
        initialMap.put((Object)"¾", (Object)"&frac34;");
        initialMap.put((Object)"¿", (Object)"&iquest;");
        initialMap.put((Object)"À", (Object)"&Agrave;");
        initialMap.put((Object)"Á", (Object)"&Aacute;");
        initialMap.put((Object)"Â", (Object)"&Acirc;");
        initialMap.put((Object)"Ã", (Object)"&Atilde;");
        initialMap.put((Object)"Ä", (Object)"&Auml;");
        initialMap.put((Object)"Å", (Object)"&Aring;");
        initialMap.put((Object)"Æ", (Object)"&AElig;");
        initialMap.put((Object)"Ç", (Object)"&Ccedil;");
        initialMap.put((Object)"È", (Object)"&Egrave;");
        initialMap.put((Object)"É", (Object)"&Eacute;");
        initialMap.put((Object)"Ê", (Object)"&Ecirc;");
        initialMap.put((Object)"Ë", (Object)"&Euml;");
        initialMap.put((Object)"Ì", (Object)"&Igrave;");
        initialMap.put((Object)"Í", (Object)"&Iacute;");
        initialMap.put((Object)"Î", (Object)"&Icirc;");
        initialMap.put((Object)"Ï", (Object)"&Iuml;");
        initialMap.put((Object)"Ð", (Object)"&ETH;");
        initialMap.put((Object)"Ñ", (Object)"&Ntilde;");
        initialMap.put((Object)"Ò", (Object)"&Ograve;");
        initialMap.put((Object)"Ó", (Object)"&Oacute;");
        initialMap.put((Object)"Ô", (Object)"&Ocirc;");
        initialMap.put((Object)"Õ", (Object)"&Otilde;");
        initialMap.put((Object)"Ö", (Object)"&Ouml;");
        initialMap.put((Object)"×", (Object)"&times;");
        initialMap.put((Object)"Ø", (Object)"&Oslash;");
        initialMap.put((Object)"Ù", (Object)"&Ugrave;");
        initialMap.put((Object)"Ú", (Object)"&Uacute;");
        initialMap.put((Object)"Û", (Object)"&Ucirc;");
        initialMap.put((Object)"Ü", (Object)"&Uuml;");
        initialMap.put((Object)"Ý", (Object)"&Yacute;");
        initialMap.put((Object)"Þ", (Object)"&THORN;");
        initialMap.put((Object)"ß", (Object)"&szlig;");
        initialMap.put((Object)"à", (Object)"&agrave;");
        initialMap.put((Object)"á", (Object)"&aacute;");
        initialMap.put((Object)"â", (Object)"&acirc;");
        initialMap.put((Object)"ã", (Object)"&atilde;");
        initialMap.put((Object)"ä", (Object)"&auml;");
        initialMap.put((Object)"å", (Object)"&aring;");
        initialMap.put((Object)"æ", (Object)"&aelig;");
        initialMap.put((Object)"ç", (Object)"&ccedil;");
        initialMap.put((Object)"è", (Object)"&egrave;");
        initialMap.put((Object)"é", (Object)"&eacute;");
        initialMap.put((Object)"ê", (Object)"&ecirc;");
        initialMap.put((Object)"ë", (Object)"&euml;");
        initialMap.put((Object)"ì", (Object)"&igrave;");
        initialMap.put((Object)"í", (Object)"&iacute;");
        initialMap.put((Object)"î", (Object)"&icirc;");
        initialMap.put((Object)"ï", (Object)"&iuml;");
        initialMap.put((Object)"ð", (Object)"&eth;");
        initialMap.put((Object)"ñ", (Object)"&ntilde;");
        initialMap.put((Object)"ò", (Object)"&ograve;");
        initialMap.put((Object)"ó", (Object)"&oacute;");
        initialMap.put((Object)"ô", (Object)"&ocirc;");
        initialMap.put((Object)"õ", (Object)"&otilde;");
        initialMap.put((Object)"ö", (Object)"&ouml;");
        initialMap.put((Object)"÷", (Object)"&divide;");
        initialMap.put((Object)"ø", (Object)"&oslash;");
        initialMap.put((Object)"ù", (Object)"&ugrave;");
        initialMap.put((Object)"ú", (Object)"&uacute;");
        initialMap.put((Object)"û", (Object)"&ucirc;");
        initialMap.put((Object)"ü", (Object)"&uuml;");
        initialMap.put((Object)"ý", (Object)"&yacute;");
        initialMap.put((Object)"þ", (Object)"&thorn;");
        initialMap.put((Object)"ÿ", (Object)"&yuml;");
        ISO8859_1_ESCAPE = Collections.unmodifiableMap((Map)initialMap);
        ISO8859_1_UNESCAPE = Collections.unmodifiableMap(EntityArrays.invert(ISO8859_1_ESCAPE));
        initialMap = new HashMap();
        initialMap.put((Object)"ƒ", (Object)"&fnof;");
        initialMap.put((Object)"Α", (Object)"&Alpha;");
        initialMap.put((Object)"Β", (Object)"&Beta;");
        initialMap.put((Object)"Γ", (Object)"&Gamma;");
        initialMap.put((Object)"Δ", (Object)"&Delta;");
        initialMap.put((Object)"Ε", (Object)"&Epsilon;");
        initialMap.put((Object)"Ζ", (Object)"&Zeta;");
        initialMap.put((Object)"Η", (Object)"&Eta;");
        initialMap.put((Object)"Θ", (Object)"&Theta;");
        initialMap.put((Object)"Ι", (Object)"&Iota;");
        initialMap.put((Object)"Κ", (Object)"&Kappa;");
        initialMap.put((Object)"Λ", (Object)"&Lambda;");
        initialMap.put((Object)"Μ", (Object)"&Mu;");
        initialMap.put((Object)"Ν", (Object)"&Nu;");
        initialMap.put((Object)"Ξ", (Object)"&Xi;");
        initialMap.put((Object)"Ο", (Object)"&Omicron;");
        initialMap.put((Object)"Π", (Object)"&Pi;");
        initialMap.put((Object)"Ρ", (Object)"&Rho;");
        initialMap.put((Object)"Σ", (Object)"&Sigma;");
        initialMap.put((Object)"Τ", (Object)"&Tau;");
        initialMap.put((Object)"Υ", (Object)"&Upsilon;");
        initialMap.put((Object)"Φ", (Object)"&Phi;");
        initialMap.put((Object)"Χ", (Object)"&Chi;");
        initialMap.put((Object)"Ψ", (Object)"&Psi;");
        initialMap.put((Object)"Ω", (Object)"&Omega;");
        initialMap.put((Object)"α", (Object)"&alpha;");
        initialMap.put((Object)"β", (Object)"&beta;");
        initialMap.put((Object)"γ", (Object)"&gamma;");
        initialMap.put((Object)"δ", (Object)"&delta;");
        initialMap.put((Object)"ε", (Object)"&epsilon;");
        initialMap.put((Object)"ζ", (Object)"&zeta;");
        initialMap.put((Object)"η", (Object)"&eta;");
        initialMap.put((Object)"θ", (Object)"&theta;");
        initialMap.put((Object)"ι", (Object)"&iota;");
        initialMap.put((Object)"κ", (Object)"&kappa;");
        initialMap.put((Object)"λ", (Object)"&lambda;");
        initialMap.put((Object)"μ", (Object)"&mu;");
        initialMap.put((Object)"ν", (Object)"&nu;");
        initialMap.put((Object)"ξ", (Object)"&xi;");
        initialMap.put((Object)"ο", (Object)"&omicron;");
        initialMap.put((Object)"π", (Object)"&pi;");
        initialMap.put((Object)"ρ", (Object)"&rho;");
        initialMap.put((Object)"ς", (Object)"&sigmaf;");
        initialMap.put((Object)"σ", (Object)"&sigma;");
        initialMap.put((Object)"τ", (Object)"&tau;");
        initialMap.put((Object)"υ", (Object)"&upsilon;");
        initialMap.put((Object)"φ", (Object)"&phi;");
        initialMap.put((Object)"χ", (Object)"&chi;");
        initialMap.put((Object)"ψ", (Object)"&psi;");
        initialMap.put((Object)"ω", (Object)"&omega;");
        initialMap.put((Object)"ϑ", (Object)"&thetasym;");
        initialMap.put((Object)"ϒ", (Object)"&upsih;");
        initialMap.put((Object)"ϖ", (Object)"&piv;");
        initialMap.put((Object)"•", (Object)"&bull;");
        initialMap.put((Object)"…", (Object)"&hellip;");
        initialMap.put((Object)"′", (Object)"&prime;");
        initialMap.put((Object)"″", (Object)"&Prime;");
        initialMap.put((Object)"‾", (Object)"&oline;");
        initialMap.put((Object)"⁄", (Object)"&frasl;");
        initialMap.put((Object)"℘", (Object)"&weierp;");
        initialMap.put((Object)"ℑ", (Object)"&image;");
        initialMap.put((Object)"ℜ", (Object)"&real;");
        initialMap.put((Object)"™", (Object)"&trade;");
        initialMap.put((Object)"ℵ", (Object)"&alefsym;");
        initialMap.put((Object)"←", (Object)"&larr;");
        initialMap.put((Object)"↑", (Object)"&uarr;");
        initialMap.put((Object)"→", (Object)"&rarr;");
        initialMap.put((Object)"↓", (Object)"&darr;");
        initialMap.put((Object)"↔", (Object)"&harr;");
        initialMap.put((Object)"↵", (Object)"&crarr;");
        initialMap.put((Object)"⇐", (Object)"&lArr;");
        initialMap.put((Object)"⇑", (Object)"&uArr;");
        initialMap.put((Object)"⇒", (Object)"&rArr;");
        initialMap.put((Object)"⇓", (Object)"&dArr;");
        initialMap.put((Object)"⇔", (Object)"&hArr;");
        initialMap.put((Object)"∀", (Object)"&forall;");
        initialMap.put((Object)"∂", (Object)"&part;");
        initialMap.put((Object)"∃", (Object)"&exist;");
        initialMap.put((Object)"∅", (Object)"&empty;");
        initialMap.put((Object)"∇", (Object)"&nabla;");
        initialMap.put((Object)"∈", (Object)"&isin;");
        initialMap.put((Object)"∉", (Object)"&notin;");
        initialMap.put((Object)"∋", (Object)"&ni;");
        initialMap.put((Object)"∏", (Object)"&prod;");
        initialMap.put((Object)"∑", (Object)"&sum;");
        initialMap.put((Object)"−", (Object)"&minus;");
        initialMap.put((Object)"∗", (Object)"&lowast;");
        initialMap.put((Object)"√", (Object)"&radic;");
        initialMap.put((Object)"∝", (Object)"&prop;");
        initialMap.put((Object)"∞", (Object)"&infin;");
        initialMap.put((Object)"∠", (Object)"&ang;");
        initialMap.put((Object)"∧", (Object)"&and;");
        initialMap.put((Object)"∨", (Object)"&or;");
        initialMap.put((Object)"∩", (Object)"&cap;");
        initialMap.put((Object)"∪", (Object)"&cup;");
        initialMap.put((Object)"∫", (Object)"&int;");
        initialMap.put((Object)"∴", (Object)"&there4;");
        initialMap.put((Object)"∼", (Object)"&sim;");
        initialMap.put((Object)"≅", (Object)"&cong;");
        initialMap.put((Object)"≈", (Object)"&asymp;");
        initialMap.put((Object)"≠", (Object)"&ne;");
        initialMap.put((Object)"≡", (Object)"&equiv;");
        initialMap.put((Object)"≤", (Object)"&le;");
        initialMap.put((Object)"≥", (Object)"&ge;");
        initialMap.put((Object)"⊂", (Object)"&sub;");
        initialMap.put((Object)"⊃", (Object)"&sup;");
        initialMap.put((Object)"⊄", (Object)"&nsub;");
        initialMap.put((Object)"⊆", (Object)"&sube;");
        initialMap.put((Object)"⊇", (Object)"&supe;");
        initialMap.put((Object)"⊕", (Object)"&oplus;");
        initialMap.put((Object)"⊗", (Object)"&otimes;");
        initialMap.put((Object)"⊥", (Object)"&perp;");
        initialMap.put((Object)"⋅", (Object)"&sdot;");
        initialMap.put((Object)"⌈", (Object)"&lceil;");
        initialMap.put((Object)"⌉", (Object)"&rceil;");
        initialMap.put((Object)"⌊", (Object)"&lfloor;");
        initialMap.put((Object)"⌋", (Object)"&rfloor;");
        initialMap.put((Object)"〈", (Object)"&lang;");
        initialMap.put((Object)"〉", (Object)"&rang;");
        initialMap.put((Object)"◊", (Object)"&loz;");
        initialMap.put((Object)"♠", (Object)"&spades;");
        initialMap.put((Object)"♣", (Object)"&clubs;");
        initialMap.put((Object)"♥", (Object)"&hearts;");
        initialMap.put((Object)"♦", (Object)"&diams;");
        initialMap.put((Object)"Œ", (Object)"&OElig;");
        initialMap.put((Object)"œ", (Object)"&oelig;");
        initialMap.put((Object)"Š", (Object)"&Scaron;");
        initialMap.put((Object)"š", (Object)"&scaron;");
        initialMap.put((Object)"Ÿ", (Object)"&Yuml;");
        initialMap.put((Object)"ˆ", (Object)"&circ;");
        initialMap.put((Object)"˜", (Object)"&tilde;");
        initialMap.put((Object)" ", (Object)"&ensp;");
        initialMap.put((Object)" ", (Object)"&emsp;");
        initialMap.put((Object)" ", (Object)"&thinsp;");
        initialMap.put((Object)"‌", (Object)"&zwnj;");
        initialMap.put((Object)"‍", (Object)"&zwj;");
        initialMap.put((Object)"‎", (Object)"&lrm;");
        initialMap.put((Object)"‏", (Object)"&rlm;");
        initialMap.put((Object)"–", (Object)"&ndash;");
        initialMap.put((Object)"—", (Object)"&mdash;");
        initialMap.put((Object)"‘", (Object)"&lsquo;");
        initialMap.put((Object)"’", (Object)"&rsquo;");
        initialMap.put((Object)"‚", (Object)"&sbquo;");
        initialMap.put((Object)"“", (Object)"&ldquo;");
        initialMap.put((Object)"”", (Object)"&rdquo;");
        initialMap.put((Object)"„", (Object)"&bdquo;");
        initialMap.put((Object)"†", (Object)"&dagger;");
        initialMap.put((Object)"‡", (Object)"&Dagger;");
        initialMap.put((Object)"‰", (Object)"&permil;");
        initialMap.put((Object)"‹", (Object)"&lsaquo;");
        initialMap.put((Object)"›", (Object)"&rsaquo;");
        initialMap.put((Object)"€", (Object)"&euro;");
        HTML40_EXTENDED_ESCAPE = Collections.unmodifiableMap((Map)initialMap);
        HTML40_EXTENDED_UNESCAPE = Collections.unmodifiableMap(EntityArrays.invert(HTML40_EXTENDED_ESCAPE));
        initialMap = new HashMap();
        initialMap.put((Object)"\"", (Object)"&quot;");
        initialMap.put((Object)"&", (Object)"&amp;");
        initialMap.put((Object)"<", (Object)"&lt;");
        initialMap.put((Object)">", (Object)"&gt;");
        BASIC_ESCAPE = Collections.unmodifiableMap((Map)initialMap);
        BASIC_UNESCAPE = Collections.unmodifiableMap(EntityArrays.invert(BASIC_ESCAPE));
        initialMap = new HashMap();
        initialMap.put((Object)"'", (Object)"&apos;");
        APOS_ESCAPE = Collections.unmodifiableMap((Map)initialMap);
        APOS_UNESCAPE = Collections.unmodifiableMap(EntityArrays.invert(APOS_ESCAPE));
        initialMap = new HashMap();
        initialMap.put((Object)"\b", (Object)"\\b");
        initialMap.put((Object)"\n", (Object)"\\n");
        initialMap.put((Object)"\t", (Object)"\\t");
        initialMap.put((Object)"\f", (Object)"\\f");
        initialMap.put((Object)"\r", (Object)"\\r");
        JAVA_CTRL_CHARS_ESCAPE = Collections.unmodifiableMap((Map)initialMap);
        JAVA_CTRL_CHARS_UNESCAPE = Collections.unmodifiableMap(EntityArrays.invert(JAVA_CTRL_CHARS_ESCAPE));
    }
}

